<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link rel="stylesheet" href="/css/stylesheet.css" />
        <title></title>
    </head>
    <body>
        <div id="site">
            <header>
                <h1 class="hidden">Header of project1 page</h1>
                <div id="headerlogo">
                </div>
                    <nav>
                        <h1 class="hidden">Menubalk van project1</h1>
                    </nav>
            </header>
            <section>
                <h1>Welkom op project 1 pagina!</h1>
                <div id="content">
                    
                </div>
                
            </section>
            <footer>project 1 &copy; 2012</footer>           
        </div>
    </body>
</html>
